[Icon Theme]
Name=Oblivion Signal
Comment=Thin monoline instrument glyphs for the Oblivion Signal theme
Inherits=Papirus-Dark,hicolor
Directories=256x256/places,256x256/mimetypes,256x256/devices,256x256/status,256x256/apps,48x48/places,48x48/mimetypes,48x48/devices,48x48/status,48x48/apps,32x32/places,32x32/mimetypes,32x32/devices,32x32/status,32x32/apps,scalable/places,scalable/mimetypes,scalable/devices,scalable/status,scalable/apps

[256x256/places]
Size=256
Type=Scalable
MinSize=24
MaxSize=512

[256x256/mimetypes]
Size=256
Type=Scalable
MinSize=24
MaxSize=512

[256x256/devices]
Size=256
Type=Scalable
MinSize=24
MaxSize=512

[256x256/status]
Size=256
Type=Scalable
MinSize=24
MaxSize=512

[256x256/apps]
Size=256
Type=Scalable
MinSize=24
MaxSize=512

[48x48/places]
Size=48
Type=Fixed

[48x48/mimetypes]
Size=48
Type=Fixed

[48x48/devices]
Size=48
Type=Fixed

[48x48/status]
Size=48
Type=Fixed

[48x48/apps]
Size=48
Type=Fixed

[scalable/places]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/apps]
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[32x32/places]
Size=32
Type=Fixed

[32x32/mimetypes]
Size=32
Type=Fixed

[32x32/devices]
Size=32
Type=Fixed

[32x32/status]
Size=32
Type=Fixed

[32x32/apps]
Size=32
Type=Fixed
