### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: OBLIVION SIGNAL
interface_branding_color: 6FA8CC
interface_help_color: 6FA8CC
interface_help_color_bright: 6FA8CC
hash_mismatch_panic: no

term_background: 0D141C
backdrop: 0D141C

# Terminal colors (Oblivion Signal palette)
term_palette: 05080C;A6455C;87AEA2;D8D9A8;6C98B7;A793AE;70A7CC;B5D2E3
term_palette_bright: 1B2A3A;C06A7C;A9CFC0;E4E5B8;C2DDF0;C4AEC4;A3CFE3;E2EFF8

# Text colors
term_foreground: B5D2E3
term_foreground_bright: B5D2E3
term_background_bright: 1B2A3A
